apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: default   # <-- adicionado namespace
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
